### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by vaer-k** [eccentric-j/cljs-tui-template#10]
I tried following the quick start, but this was my experience:

```
lein new cljs-tui my-test-project
cd my-test-project
npm run init
```

```
[:app] Build completed. (120 files, 2 compiled, 2 warnings, 2.02s)

------ WARNING #1 - :undeclared-var --------------------------------------------
 Resource: clojure/tools/cli.cljc:126:17
--------------------------------------------------------------------------------
 123 |          (recur options (into extra-args (vec (rest args))) nil)
 124 |
 125 |          (and (opt? opt) (nil? spec))
 126 |          (throw (Exception. (str "'" opt "' is not a valid argument")))
-----------------------^--------------------------------------------------------
 Use of undeclared Var clojure.tools.cli/Exception
--------------------------------------------------------------------------------
 127 |
 128 |          (and (opt? opt) (spec :flag))
 129 |          (recur ((spec :assoc-fn) options (spec :name) (flag-for opt))
 130 |                 extra-args
--------------------------------------------------------------------------------

------ WARNING #2 - :undeclared-var --------------------------------------------
 Resource: clojure/tools/cli.cljc:228:25
--------------------------------------------------------------------------------
 225 |   (when *assert*
 226 |     (let [unknown-keys (keys (apply dissoc map spec-keys))]
 227 |       (when (seq unknown-keys)
 228 |         (binding [*out* *err*]
-------------------------------^------------------------------------------------
 Use of undeclared Var clojure.tools.cli/*err*
--------------------------------------------------------------------------------
 229 |           (println (str "Warning: The following options to parse-opts are unrecognized: "
 230 |                         (s/join ", " unknown-keys)))))))
 231 |
 232 |   (select-keys map spec-keys))
--------------------------------------------------------------------------------
```

```
➜  mytest node --inspect target/js/compiled/my-test-project.js
Debugger listening on ws://127.0.0.1:9229/f2be31d5-b8b8-4c10-870b-de6662521801
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/Users/vraerek/src/mytest/target/js/compiled/my-test-project.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by vaer-k** [comment]
My mistake 🤦‍♂

**Comment by jaidetree** [comment]
I'm glad it's resolved. May I ask what your issue was? Is there anything I can add to the docs to make the process smoother?

**Comment by vaer-k** [comment]
Nope. It was a pretty silly mistake on my part. I'd inadvertently changed the name of the project slightly when I created it, so when I ran the node command verbatim it was looking for a different compilation target
